### ISSUE TITLE
Bug in page 17 of the documentation (keyvaltable v2.0)

### ISSUE THREAD

**Issue by quark67** [Ri-Ga/keyvaltable#1] opened 2019-06-03 11:48 UTC
The text of section 7.1 continue below the page number 17 and the text of section 7.2 is partially cut below the page number 17.

![image](https://user-images.githubusercontent.com/9338576/58799658-2f1f0a80-8606-11e9-87fb-753fda6ad04b.png)

**Comment by Ri-Ga** [comment] 2019-06-09 22:25
Thanks for reporting this!
The issue is fixed in 3781646b5cbb061550b9bca67303c3517825567a.
Note: The problem was caused by the use of any of longtable/xltabular/longtabu inside a figure environment, which apparently confused the page layouting algorithm. Normally, using such an environment in a float (figure/table) does not make sense, because the environments provide floating capabilities themselves. Here, however, the environments are used in a figure for demonstration only and could not easily be used differently. The solution therefore was to force page breaking via `\clearpage`.

**Closed as completed by Ri-Ga** 2019-06-09 22:25 UTC
Labels: bug
